/*
 * lib_LIS3DSH.h
 *
 *  Created on: 7 sty 2015
 *      Author: mike
 */

#ifndef LIB_LIS3DSH_H_
#define LIB_LIS3DSH_H_		/* LIB_LIS3DSH_H_ */

#define LIS3DSH_INFO1_ADDR 				(0x0D)
#define LIS3DSH_INFO2_ADDR 				(0x0E)
#define LIS3DSH_WHO_AM_I_ADDR 			(0x0F)

/* CTRL_REG3 */
#define LIS3DSH_CTRL3_ADDR				(0x23)
#define LIS3DSH_CTRL3_DR_EN_BIT			(1 << 7)
#define LIS3DSH_CTRL3_IEA_BIT			(1 << 6)
#define LIS3DSH_CTRL3_IEL_BIT			(1 << 5)
#define LIS3DSH_CTRL3_INT2_EN_BIT		(1 << 4)
#define LIS3DSH_CTRL3_INT1_EN_BIT		(1 << 3)
#define LIS3DSH_CTRL3_VFILT_BIT			(1 << 2)
#define LIS3DSH_CTRL3_STRT_BIT			(1 << 0)


/* CTRL_REG4 */
#define LIS3DSH_CTRL4_ADDR				(0x20)
#define LIS3DSH_CTRL4_ODR_OFFSET		(4)
#define LIS3DSH_CTRL4_ODR_BM			(0b1111 << LIS3DSH_CTRL4_ODR_OFFSET)
#define LIS3DSH_CTRL4_ODR_PDOWN			(0 << LIS3DSH_CTRL4_ODR_OFFSET)
#define LIS3DSH_CTRL4_ODR_3Hz			(1 << LIS3DSH_CTRL4_ODR_OFFSET)
#define LIS3DSH_CTRL4_ODR_6Hz			(2 << LIS3DSH_CTRL4_ODR_OFFSET)
#define LIS3DSH_CTRL4_ODR_12Hz			(3 << LIS3DSH_CTRL4_ODR_OFFSET)
#define LIS3DSH_CTRL4_ODR_25Hz			(4 << LIS3DSH_CTRL4_ODR_OFFSET)
#define LIS3DSH_CTRL4_ODR_50Hz 			(5 << LIS3DSH_CTRL4_ODR_OFFSET)
#define LIS3DSH_CTRL4_ODR_100Hz			(6 << LIS3DSH_CTRL4_ODR_OFFSET)
#define LIS3DSH_CTRL4_ODR_400Hz			(7 << LIS3DSH_CTRL4_ODR_OFFSET)
#define LIS3DSH_CTRL4_ODR_800Hz			(8 << LIS3DSH_CTRL4_ODR_OFFSET)
#define LIS3DSH_CTRL4_ODR_1600Hz		(9 << LIS3DSH_CTRL4_ODR_OFFSET)
#define LIS3DSH_CTRL4_BDU_BIT			(1 << 3)						// Block Data Updata - 0
#define LIS3DSH_CTRL4_Z_ENABLE_BIT		(1 << 2)
#define LIS3DSH_CTRL4_Y_ENABLE_BIT		(1 << 1)
#define LIS3DSH_CTRL4_X_ENABLE_BIT		(1 << 0)
#define LIS3DSH_CTRL4_XYZ_ENABLE_BIT    (LIS3DSH_CTRL4_X_ENABLE_BIT | LIS3DSH_CTRL4_Y_ENABLE_BIT | LIS3DSH_CTRL4_Z_ENABLE_BIT)

/* CTRL_REG5 */
#define LIS3DSH_CTRL5_ADDR				(0x24)
#define LIS3DSH_CTRL5_BW_OFFSET			(6)
#define LIS3DSH_CTRL5_BW_BM				(0b11 << LIS3DSH_CTRL5_BW_OFFSET)
#define LIS3DSH_CTRL5_BW_800Hz			(0 << LIS3DSH_CTRL5_BW_OFFSET )
#define LIS3DSH_CTRL5_BW_400Hz			(1 << LIS3DSH_CTRL5_BW_OFFSET )
#define LIS3DSH_CTRL5_BW_200Hz			(2 << LIS3DSH_CTRL5_BW_OFFSET )
#define LIS3DSH_CTRL5_BW_50Hz			(3 << LIS3DSH_CTRL5_BW_OFFSET )

#define LIS3DSH_CTRL5_FSCALE_OFFSET		(3)
#define LIS3DSH_CTRL5_FSCALE_BM			(0b111 << LIS3DSH_CTRL5_FSCALE_OFFSET)
#define LIS3DSH_CTRL5_FSCALE_2G			(0 << LIS3DSH_CTRL5_FSCALE_OFFSET)
#define LIS3DSH_CTRL5_FSCALE_4G			(1 << LIS3DSH_FSCALE_2G)
#define LIS3DSH_CTRL5_FSCALE_6G			(2 << LIS3DSH_CTRL5_FSCALE_OFFSET)
#define LIS3DSH_CTRL5_FSCALE_8G			(3 << LIS3DSH_CTRL5_FSCALE_OFFSET)
#define LIS3DSH_CTRL5_FSCALE_16G		(4 << LIS3DSH_CTRL5_FSCALE_OFFSET)

#define LIS3DSH_CTRL5_ST_OFFSET			(1)
#define LIS3DSH_CTRL5_ST_BM				(0b11 << LIS3DSH_CTRL5_ST_OFFSET)
#define LIS3DSH_CTRL5_ST_NORMAL_MODE	(0 << LIS3DSH_CTRL5_ST_OFFSET)
#define LIS3DSH_CTRL5_ST_POS_SIGN		(1 << LIS3DSH_CTRL5_ST_OFFSET)
#define LIS3DSH_CTRL5_ST_NEG_SIGN		(2 << LIS3DSH_CTRL5_ST_OFFSET)
#define LIS3DSH_CTRL5_ST_NOT_ALLOWED	(3 << LIS3DSH_CTRL5_ST_OFFSET)

/* CTRL_REG_6 */
#define LIS3DSH_CTRL6_ADDR				(0x25)
#define LIS3DSH_CTRL6_BOOT_BIT			(1 << 7)
#define LIS3DSH_CTRL6_FIFO_EN_BIT		(1 << 6)
#define LIS3DSH_CTRL6_WTM_EN_BIT		(1 << 5)
#define LIS3DSH_CTRL6_ADD_INC_BIT		(1 << 4)
#define LIS3DSH_CTRL6_P1_EMPTY_BIT		(1 << 3)
#define LIS3DSH_CTRL6_P1_WTM_BIT		(1 << 2)
#define LIS3DSH_CTRL6_P1_OVERRUN_BIT	(1 << 1)
#define LIS3DSH_CTRL6_P2_BOT_BIT		(1 << 0)

/* STATUS REGISTER */
#define LIS3DSH_STATUS_ADDR				(0x27)
#define LIS3DSH_STATUS_ZYXOR_BIT 		(1 << 7) // OVERRUN
#define LIS3DSH_STATUS_ZOR_BIT			(1 << 6)
#define LIS3DSH_STATUS_YOR_BIT			(1 << 5)
#define LIS3DSH_STATUS_XOR_BIT			(1 << 4) // DATA AVAILABLE
#define LIS3DSH_STATUS_ZYXDA_BIT		(1 << 3)
#define LIS3DSH_STATUS_ZDA_BIT			(1 << 2)
#define LIS3DSH_STATUS_YDA_BIT			(1 << 1)
#define LIS3DSH_STATUS_XDA_BIT			(1 << 0)

/* OUT_T - temperature output register */
#define LIS3DSH_OUT_T_ADDR	 			(0x0C)	// !LSB/deg value is expresse as two's complement

/* OFFSET CORRECTION - signed values */
#define LIS3DSH_OFF_X_ADDR				(0x10)
#define LIS3DSH_OFF_Y_ADDR				(0x11)
#define LIS3DSH_OFF_Z_ADDR				(0x12)

/* CONSTANT SHIFT */
#define LIS3DSH_CS_X_ADDR				(0x13)	// singned valuses, state-machine only
#define LIS3DSH_CS_Y_ADDR				(0x14)
#define LIS3DSH_CS_Z_ADDR				(0x15)


/* 160bit counter-register for interrupt state machine programs timing */
#define LIS3DSH_LC_L_ADDR				(0x16)
#define LIS3DSH_LC_H_ADDR				(0x17)

/* STAT - INTERRUPT STATUS REGISTER */
#define LIS3DSH_STAT_ADDR				(0x18)
#define LIS3DSH_STAT_DRDY_BIT			(1 << 0)
#define LIS3DSH_STAT_DOR_BIT			(1 << 1)
#define LIS3DSH_STAT_INT_SM2_BIT		(1 << 2)
#define LIS3DSH_STAT_INT_SM1_BIT		(1 << 3)
#define LIS3DSH_STAT_SYNC2_BIT			(1 << 4)
#define LIS3DSH_STAT_SYNC1_BIT			(1 << 5)
#define LIS3DSH_STAT_SYNCW_BIT			(1 << 6)
#define LIS3DSH_STAT_LONG_BIT			(1 << 7)

/* VFC_x - Vector coefficient reg 1 forDiff filter */
#define LIS3DSH_VFC_1_ADDR				(0x1b)
#define LIS3DSH_VFC_2_ADDR				(0x1c)
#define LIS3DSH_VFC_3_ADDR				(0x1d)
#define LIS3DSH_VFC_4_ADDR				(0x1e)

/* THRS3 - Threshold value register */
#define LIS3DSH_THRS3_ADDR				(0x1f)


/* OUTPUT REGITER */
#define LIS3DSH_OUT_XL 					(0x28)
#define LIS3DSH_OUT_XH					(0x29)
#define LIS3DSH_OUT_YL					(0x2A)
#define LIS3DSH_OUT_YH 					(0x2B)
#define LIS3DSH_OUT_ZL 					(0x2C)
#define LIS3DSH_OUT_ZH 					(0x2D)



/* FIFO_CTRL - FIFO control reg */
#define LIS3DSH_FIFO_CTRL_ADDR	(0x2e)
#define LIS3DSH_FIFO_CTRL_FMODE_OFFSET				(5)
#define LIS3DSH_FIFO_CTRL_FMODE_BM					(0b111 << LIS3DSH_FIFO_CTRL_FMODE_OFFSET)
#define LIS3DSH_FIFO_CTRL_FMODE_BYPASS				(0 << LIS3DSH_FIFO_CTRL_FMODE_OFFSET)
#define LIS3DSH_FIFO_CTRL_FMODE_FIFO				(1 << LIS3DSH_FIFO_CTRL_FMODE_OFFSET)
#define LIS3DSH_FIFO_CTRL_FMODE_STREAM				(2 << LIS3DSH_FIFO_CTRL_FMODE_OFFSET)
#define LIS3DSH_FIFO_CTRL_FMODE_STREAM_TO_FIFO		(3 << LIS3DSH_FIFO_CTRL_FMODE_OFFSET)
#define LIS3DSH_FIFO_CTRL_FMODE_BYPASS_TO_STREAM	(4 << LIS3DSH_FIFO_CTRL_FMODE_OFFSET)
#define LIS3DSH_FIFO_CTRL_FMODE_BYPASS_TO_FIFO		(8 << LIS3DSH_FIFO_CTRL_FMODE_OFFSET)
#define LIS3DSH_FIFO_CTRL_WTMP_OFFSET				(0)											// FIFO watermark pointer
#define LIS3DSH_FIFO_CTRL_WTMP_BM					(0b11111 << LIS3DSH_FIFO_CTRL_WTMP_OFFSET)


/* FIFO_SRC */
#define LIS3DSH_FIFO_SRC_ADDR				(0x2f)
#define LIS3DSH_FIFO_SRC_WTM_BIT			(1 << 7)
#define LIS3DSH_FIFO_SRC_OVRN_FIFO_BIT 		(1 << 6)
#define LIS3DSH_FIFO_SRC_EMPTY_BIT			(1 << 5)
#define LIS3DSH_FIFO_SRC_FSS_BM				(0b11111)

/* CTRL_REG1 */
#define LIS3DSH_CTRL1_ADDR					(0x21)
#define LIS3DSH_CTRL1_HYST1_OFFSET 			(5)
#define LIS3DSH_CTRL1_HYST1_BM				(0b111 << LIS3DSH_CTRL1_HYST1_OFFSET)
#define LIS3DSH_CTRL1_SM1_PIN_BIT			(1 << 3)
#define LIS3DSH_CTRL1_SM1_EN_BIT			(1 << 0)

/*
 * Reszta rejestrów dotyczy konfiguracji pracy maszyn stamu
 */




#endif /* LIB_LIS3DSH_H_ */




